# Generated by Django 4.0.4 on 2022-04-30 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='MovieActors',
        ),
        migrations.CreateModel(
            name='Joint',
            fields=[
                ('JointId', models.AutoField(primary_key=True, serialize=False)),
                ('ActorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoviesApp.actors')),
                ('MovieId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoviesApp.movies')),
            ],
        ),
    ]
