# Generated by Django 4.0.4 on 2022-05-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesApp', '0002_remove_movies_movieactors_joint'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='MovieDownVote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movies',
            name='MovieUpVote',
            field=models.IntegerField(default=0),
        ),
    ]
