# Generated by Django 4.0.4 on 2022-05-03 06:01

from django.db import migrations

def add_new_relation(apps, schema_editor):
    Joint = apps.get_model("MoviesApp", "Joint")
    Actors = apps.get_model("MoviesApp", "Actors")
    Movies = apps.get_model("MoviesApp", "Movies")

    """ l = 0

    for joint in Joint.objects.all():
        l += 1

    l += 1 """

    actorId = Actors.objects.get(ActorName = "NTR")
    movieId = Movies.objects.get(MovieTitle = "KGF 2")

    new_entry = Joint(MovieId = movieId, ActorId = actorId)
    new_entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesApp', '0003_movies_moviedownvote_movies_movieupvote'),
    ]

    operations = [
        migrations.RunPython(add_new_relation)
    ]
